// 낱말 라운드 단어 풀 — 우리가 만든 710문장에서 빈도순으로 뽑아 뜻을 직접 붙였다.
// (시판 교재에서 추출한 목록은 저작권 때문에 쓰지 않는다 — 사용자 지시)
// en은 3~8글자 소문자만. 칩 조립이라 아포스트로피·대문자·공백 없는 단어만 넣는다.
export const WORDS = [
  // 명사
  { en: 'baby', ko: '아기' },
  { en: 'book', ko: '책' },
  { en: 'music', ko: '음악' },
  { en: 'room', ko: '방' },
  { en: 'letter', ko: '편지' },
  { en: 'night', ko: '밤' },
  { en: 'rain', ko: '비' },
  { en: 'snow', ko: '눈 (하늘에서 오는)' },
  { en: 'story', ko: '이야기' },
  { en: 'news', ko: '소식, 뉴스' },
  { en: 'bird', ko: '새' },
  { en: 'door', ko: '문' },
  { en: 'friend', ko: '친구' },
  { en: 'bread', ko: '빵' },
  { en: 'lunch', ko: '점심' },
  { en: 'dinner', ko: '저녁 식사' },
  { en: 'flower', ko: '꽃' },
  { en: 'sky', ko: '하늘' },
  { en: 'sister', ko: '여동생, 언니' },
  { en: 'brother', ko: '남동생, 형' },
  { en: 'morning', ko: '아침' },
  { en: 'water', ko: '물' },
  { en: 'shoes', ko: '신발' },
  { en: 'joke', ko: '농담' },
  { en: 'food', ko: '음식' },
  { en: 'wind', ko: '바람' },
  { en: 'school', ko: '학교' },
  { en: 'cake', ko: '케이크' },
  { en: 'apple', ko: '사과' },
  { en: 'song', ko: '노래' },
  { en: 'bike', ko: '자전거' },
  { en: 'class', ko: '수업, 반' },
  { en: 'map', ko: '지도' },
  { en: 'candy', ko: '사탕' },
  { en: 'wall', ko: '벽' },
  { en: 'blanket', ko: '담요' },
  { en: 'movie', ko: '영화' },
  { en: 'rice', ko: '쌀, 밥' },
  { en: 'uncle', ko: '삼촌' },
  { en: 'farmer', ko: '농부' },
  { en: 'kite', ko: '연' },
  { en: 'box', ko: '상자' },
  { en: 'gift', ko: '선물' },
  { en: 'photo', ko: '사진' },
  { en: 'coach', ko: '코치, 감독' },
  { en: 'hat', ko: '모자' },
  { en: 'team', ko: '팀' },
  { en: 'ticket', ko: '표, 티켓' },
  { en: 'window', ko: '창문' },
  { en: 'park', ko: '공원' },
  { en: 'doctor', ko: '의사' },
  { en: 'nurse', ko: '간호사' },
  { en: 'teacher', ko: '선생님' },
  { en: 'student', ko: '학생' },
  { en: 'cook', ko: '요리사' },
  { en: 'pilot', ko: '조종사' },
  { en: 'hand', ko: '손' },
  { en: 'star', ko: '별' },
  { en: 'fish', ko: '물고기' },
  { en: 'bell', ko: '종' },
  { en: 'train', ko: '기차' },
  { en: 'city', ko: '도시' },
  { en: 'summer', ko: '여름' },
  { en: 'autumn', ko: '가을' },
  { en: 'winter', ko: '겨울' },
  { en: 'spring', ko: '봄' },
  { en: 'soup', ko: '수프' },
  { en: 'captain', ko: '선장, 주장' },
  { en: 'grandma', ko: '할머니' },
  { en: 'grandpa', ko: '할아버지' },
  // 형용사
  { en: 'happy', ko: '행복한' },
  { en: 'sad', ko: '슬픈' },
  { en: 'warm', ko: '따뜻한' },
  { en: 'cold', ko: '추운, 차가운' },
  { en: 'hot', ko: '뜨거운, 더운' },
  { en: 'tired', ko: '피곤한' },
  { en: 'clean', ko: '깨끗한' },
  { en: 'sweet', ko: '달콤한' },
  { en: 'good', ko: '좋은' },
  { en: 'new', ko: '새로운' },
  { en: 'old', ko: '오래된, 나이 든' },
  { en: 'big', ko: '큰' },
  { en: 'little', ko: '작은, 어린' },
  { en: 'easy', ko: '쉬운' },
  { en: 'hard', ko: '어려운, 딱딱한' },
  { en: 'sleepy', ko: '졸린' },
  { en: 'fast', ko: '빠른' },
  { en: 'kind', ko: '친절한' },
  { en: 'nice', ko: '멋진, 좋은' },
  { en: 'glad', ko: '기쁜' },
  { en: 'strong', ko: '강한, 힘센' },
  { en: 'soft', ko: '부드러운' },
  { en: 'funny', ko: '웃긴' },
  { en: 'dark', ko: '어두운' },
  { en: 'wet', ko: '젖은' },
  { en: 'heavy', ko: '무거운' },
  { en: 'sour', ko: '(맛이) 신' },
  { en: 'blue', ko: '파란' },
  { en: 'busy', ko: '바쁜' },
  { en: 'loud', ko: '시끄러운' },
  { en: 'ready', ko: '준비된' },
  { en: 'smart', ko: '똑똑한' },
  { en: 'hungry', ko: '배고픈' },
  // 동사
  { en: 'run', ko: '달리다' },
  { en: 'sing', ko: '노래하다' },
  { en: 'swim', ko: '수영하다' },
  { en: 'walk', ko: '걷다' },
  { en: 'sleep', ko: '자다' },
  { en: 'grow', ko: '자라다, 기르다' },
  { en: 'eat', ko: '먹다' },
  { en: 'read', ko: '읽다' },
  { en: 'draw', ko: '그리다' },
  { en: 'tell', ko: '말해 주다' },
  { en: 'buy', ko: '사다' },
  { en: 'give', ko: '주다' },
  { en: 'make', ko: '만들다' },
  { en: 'keep', ko: '유지하다, 지키다' },
  { en: 'find', ko: '찾다, 발견하다' },
  { en: 'play', ko: '놀다, (경기를) 하다' },
  { en: 'open', ko: '열다' },
  { en: 'watch', ko: '보다, 지켜보다' },
  { en: 'teach', ko: '가르치다' },
  { en: 'send', ko: '보내다' },
  { en: 'call', ko: '부르다, 전화하다' },
  { en: 'smile', ko: '미소 짓다' },
  { en: 'jump', ko: '뛰어오르다' },
  { en: 'fall', ko: '떨어지다' },
  { en: 'shine', ko: '빛나다' },
  { en: 'cry', ko: '울다' },
  { en: 'live', ko: '살다' },
  { en: 'love', ko: '사랑하다' },
  { en: 'want', ko: '원하다' },
  { en: 'know', ko: '알다' },
  { en: 'drink', ko: '마시다' },
  { en: 'wait', ko: '기다리다' },
  { en: 'study', ko: '공부하다' },
  { en: 'paint', ko: '(물감으로) 칠하다' },
  { en: 'solve', ko: '(문제를) 풀다' },
  { en: 'ride', ko: '타다' },
  { en: 'cheer', ko: '응원하다' },
  { en: 'taste', ko: '맛이 나다' },
  { en: 'sound', ko: '~하게 들리다' },
  { en: 'feel', ko: '느끼다' },
];

export const WORD_BY_EN = new Map(WORDS.map((w) => [w.en, w]));
